[package]
name = "nightbreak"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = "0.28.0"
log = { version = "0.4", features = ["max_level_off"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"